from django.urls import path, include
from .views import BookList
from rest_framework.routers import DefaultRouter
urlpatterns = [
    path('books/', BookList.as_view(), name='book-list'),
]

from .views import BookViewSet
router = DefaultRouter()
router.register(r'books_all', BookViewSet, basename='book_all')

urlpatterns = [
    # Existing ListAPIView route (optional if you no longer need it)
    path('books/', BookList.as_view(), name='book-list'),

    # Include the router URLs for CRUD operations
    path('', include(router.urls)),
]# Routes generated by the router

